import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { Inter, Outfit } from "next/font/google";
import Footer from "../components/Footer";
import "./globals.css";
// import Navbar from "@/components/Navbar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${outfit.variable} antialiased font-inter`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
