export interface FDAApproval {
  id: string;
  dateOfFinalDecision: string;
  submissionNumber: string;
  device: string;
  company: string;
  panel: string;
  primaryProductCode: string;
}

export const mockData: FDAApproval[] = [
  {
    id: "1",
    dateOfFinalDecision: "11/15/2024",
    submissionNumber: "K242062",
    device: "1CMR Pro",
    company: "Mycardium AI Limited",
    panel: "Pathology",
    primaryProductCode: "NMN",
  },
  {
    id: "2",
    dateOfFinalDecision: "06/26/1998",
    submissionNumber: "P970058",
    device: "M1000 IMAGECHECKER",
    company: "Hologic, Inc.",
    panel: "Radiology",
    primaryProductCode: "MYN",
  },
  {
    id: "3",
    dateOfFinalDecision: "09/02/1998",
    submissionNumber: "P980025",
    device: "AUTOPAP(R) 300 QC AUTOMATIC PAP SCREENERQC SYSTEM",
    company: "BD DIAGNOSTICS",
    panel: "Pathology",
    primaryProductCode: "MNM",
  },
  {
    id: "4",
    dateOfFinalDecision: "09/02/1998",
    submissionNumber: "K003301",
    device: "RAPIDSCREEN RS-2000",
    company: "RIVERAIN MEDICAL GRO",
    panel: "Radiology",
    primaryProductCode: "MYN",
  },
  {
    id: "5",
    dateOfFinalDecision: "03/16/2006",
    submissionNumber: "P040028",
    device: "LUMA CERVICAL IMAGING SYSTEM",
    company: "SPECTRA SCIENCE",
    panel: "Obstetrics/Gynecology",
    primaryProductCode: "MWM",
  },
  {
    id: "6",
    dateOfFinalDecision: "07/17/2008",
    submissionNumber: "K081140",
    device: "VISENSIA",
    company: "OBS MEDICAL",
    panel: "Cardiovascular",
    primaryProductCode: "MHX",
  },
  {
    id: "7",
    dateOfFinalDecision: "05/15/2008",
    submissionNumber: "K080762",
    device: "IB NEURO, VERSION 1.0",
    company: "IMAGING BIOMETRICS, LL",
    panel: "Radiology",
    primaryProductCode: "LNH",
  },
  {
    id: "8",
    dateOfFinalDecision: "07/30/2008",
    submissionNumber: "K080896",
    device: "PATHWORK DIAGNOSTICS TISSUE OF ORIGIN TEST",
    company: "PATHWORK DIAGNOSTIC",
    panel: "Clinical Toxicology",
    primaryProductCode: "OIW",
  },
  {
    id: "9",
    dateOfFinalDecision: "09/02/1992",
    submissionNumber: "P903325",
    device: "AUTOPAP(R) 340 QC AUTOMATIC PAP SCREENERQC SYSTEM",
    company: "BD DIAGNOSTICS",
    panel: "Toxicology",
    primaryProductCode: "OIM",
  },
  {
    id: "10",
    dateOfFinalDecision: "09/02/1988",
    submissionNumber: "K003301",
    device: "RAPIDSCREEN RS-2000",
    company: "RIVERAIN MEDICAL GRO",
    panel: "Toxicology",
    primaryProductCode: "MYN",
  },
  {
    id: "11",
    dateOfFinalDecision: "03/16/2003",
    submissionNumber: "P045028",
    device: "LUMA CERVICAL IMAGING SYSTEM",
    company: "SPECTRA SCIENCE",
    panel: "Obstetrics/Gynecology",
    primaryProductCode: "MWM",
  },
  {
    id: "12",
    dateOfFinalDecision: "07/17/2708",
    submissionNumber: "K081140",
    device: "VISENSIA",
    company: "OBS MEDICAL",
    panel: "Cardiovascular",
    primaryProductCode: "MHX",
  },
  {
    id: "13",
    dateOfFinalDecision: "05/15/2208",
    submissionNumber: "K080762",
    device: "IB NEURO, VERSION 1.0",
    company: "IMAGING BIOMETRICS, LL",
    panel: "Cardiovascular",
    primaryProductCode: "MHX",
  },
  {
    id: "14",
    dateOfFinalDecision: "07/30/2010",
    submissionNumber: "K080896",
    device: "PATHWORK DIAGNOSTICS TISSUE OF ORIGIN TEST",
    company: "PATHWORK DIAGNOSTIC",
    panel: "Clinical Toxicology",
    primaryProductCode: "OWX",
  },
  {
    id: "15",
    dateOfFinalDecision: "09/02/1993",
    submissionNumber: "P930025",
    device: "AUTOPAP(R) 300 QC AUTOMATIC PAP SCREENERQC SYSTEM",
    company: "BD DIAGNOSTICS",
    panel: "Pathology",
    primaryProductCode: "MYM",
  },
  {
    id: "16",
    dateOfFinalDecision: "09/02/1978",
    submissionNumber: "K003301",
    device: "RAPIDSCREEN RS-2000",
    company: "RIVERAIN MEDICAL GRO",
    panel: "Radiology",
    primaryProductCode: "MTN",
  },
  {
    id: "17",
    dateOfFinalDecision: "03/16/2009",
    submissionNumber: "P040028",
    device: "LUMA CERVICAL IMAGING SYSTEM",
    company: "SPECTRA SCIENCE",
    panel: "Obstetrics/Gynecology",
    primaryProductCode: "MEM",
  },
  {
    id: "18",
    dateOfFinalDecision: "07/17/2002",
    submissionNumber: "K081140",
    device: "VISENSIA",
    company: "OBS MEDICAL",
    panel: "Cardiovascular",
    primaryProductCode: "MHS",
  },
  {
    id: "19",
    dateOfFinalDecision: "05/15/2010",
    submissionNumber: "K080762",
    device: "IB NEURO, VERSION 1.0",
    company: "IMAGING BIOMETRICS, LL",
    panel: "Radiology",
    primaryProductCode: "LNW",
  },
  {
    id: "20",
    dateOfFinalDecision: "07/30/2011",
    submissionNumber: "K080896",
    device: "PATHWORK DIAGNOSTICS TISSUE OF ORIGIN TEST",
    company: "PATHWORK DIAGNOSTIC",
    panel: "Clinical Toxicology",
    primaryProductCode: "ORW",
  },
  {
    id: "21",
    dateOfFinalDecision: "07/30/2003",
    submissionNumber: "K083896",
    device: "PATHWORK DIAGNOSTICS TISSUE OF ORIGIN TEST",
    company: "PATHWORK DIAGNOSTIC",
    panel: "Clinical Toxicology",
    primaryProductCode: "OOW",
  },
];
