import { FDAApproval } from "@/types/fda.types";

export const mockData: FDAApproval[] = [
  {
    id: "1",
    date_of_final_decision: "11/15/2024",
    submission_number: "K242062",
    device: "1CMR Pro",
    company: "Mycardium AI Limited",
    panel_lead: "Pathology",
    primary_product_code: "NMN",
  },
  {
    id: "2",
    date_of_final_decision: "06/26/1998",
    submission_number: "P970058",
    device: "M1000 IMAGECHECKER",
    company: "Hologic, Inc.",
    panel_lead: "Radiology",
    primary_product_code: "MYN",
  },
  {
    id: "3",
    date_of_final_decision: "09/02/1998",
    submission_number: "P980025",
    device: "AUTOPAP(R) 300 QC AUTOMATIC PAP SCREENERQC SYSTEM",
    company: "BD DIAGNOSTICS",
    panel_lead: "Pathology",
    primary_product_code: "MNM",
  },
  {
    id: "4",
    date_of_final_decision: "09/02/1998",
    submission_number: "K003301",
    device: "RAPIDSCREEN RS-2000",
    company: "RIVERAIN MEDICAL GRO",
    panel_lead: "Radiology",
    primary_product_code: "MYN",
  },
  {
    id: "5",
    date_of_final_decision: "03/16/2006",
    submission_number: "P040028",
    device: "LUMA CERVICAL IMAGING SYSTEM",
    company: "SPECTRA SCIENCE",
    panel_lead: "Obstetrics/Gynecology",
    primary_product_code: "MWM",
  },
  {
    id: "6",
    date_of_final_decision: "07/17/2008",
    submission_number: "K081140",
    device: "VISENSIA",
    company: "OBS MEDICAL",
    panel_lead: "Cardiovascular",
    primary_product_code: "MHX",
  },
  {
    id: "7",
    date_of_final_decision: "05/15/2008",
    submission_number: "K080762",
    device: "IB NEURO, VERSION 1.0",
    company: "IMAGING BIOMETRICS, LL",
    panel_lead: "Radiology",
    primary_product_code: "LNH",
  },
  {
    id: "8",
    date_of_final_decision: "07/30/2008",
    submission_number: "K080896",
    device: "PATHWORK DIAGNOSTICS TISSUE OF ORIGIN TEST",
    company: "PATHWORK DIAGNOSTIC",
    panel_lead: "Clinical Toxicology",
    primary_product_code: "OIW",
  },
  {
    id: "9",
    date_of_final_decision: "09/02/1992",
    submission_number: "P903325",
    device: "AUTOPAP(R) 340 QC AUTOMATIC PAP SCREENERQC SYSTEM",
    company: "BD DIAGNOSTICS",
    panel_lead: "Toxicology",
    primary_product_code: "OIM",
  },
  {
    id: "10",
    date_of_final_decision: "09/02/1988",
    submission_number: "K003301",
    device: "RAPIDSCREEN RS-2000",
    company: "RIVERAIN MEDICAL GRO",
    panel_lead: "Toxicology",
    primary_product_code: "MYN",
  },
  {
    id: "11",
    date_of_final_decision: "03/16/2003",
    submission_number: "P045028",
    device: "LUMA CERVICAL IMAGING SYSTEM",
    company: "SPECTRA SCIENCE",
    panel_lead: "Obstetrics/Gynecology",
    primary_product_code: "MWM",
  },
  {
    id: "12",
    date_of_final_decision: "07/17/2708",
    submission_number: "K081140",
    device: "VISENSIA",
    company: "OBS MEDICAL",
    panel_lead: "Cardiovascular",
    primary_product_code: "MHX",
  },
  {
    id: "13",
    date_of_final_decision: "05/15/2208",
    submission_number: "K080762",
    device: "IB NEURO, VERSION 1.0",
    company: "IMAGING BIOMETRICS, LL",
    panel_lead: "Cardiovascular",
    primary_product_code: "MHX",
  },
  {
    id: "14",
    date_of_final_decision: "07/30/2010",
    submission_number: "K080896",
    device: "PATHWORK DIAGNOSTICS TISSUE OF ORIGIN TEST",
    company: "PATHWORK DIAGNOSTIC",
    panel_lead: "Clinical Toxicology",
    primary_product_code: "OWX",
  },
  {
    id: "15",
    date_of_final_decision: "09/02/1993",
    submission_number: "P930025",
    device: "AUTOPAP(R) 300 QC AUTOMATIC PAP SCREENERQC SYSTEM",
    company: "BD DIAGNOSTICS",
    panel_lead: "Pathology",
    primary_product_code: "MYM",
  },
  {
    id: "16",
    date_of_final_decision: "09/02/1978",
    submission_number: "K003301",
    device: "RAPIDSCREEN RS-2000",
    company: "RIVERAIN MEDICAL GRO",
    panel_lead: "Radiology",
    primary_product_code: "MTN",
  },
  {
    id: "17",
    date_of_final_decision: "03/16/2009",
    submission_number: "P040028",
    device: "LUMA CERVICAL IMAGING SYSTEM",
    company: "SPECTRA SCIENCE",
    panel_lead: "Obstetrics/Gynecology",
    primary_product_code: "MEM",
  },
  {
    id: "18",
    date_of_final_decision: "07/17/2002",
    submission_number: "K081140",
    device: "VISENSIA",
    company: "OBS MEDICAL",
    panel_lead: "Cardiovascular",
    primary_product_code: "MHS",
  },
  {
    id: "19",
    date_of_final_decision: "05/15/2010",
    submission_number: "K080762",
    device: "IB NEURO, VERSION 1.0",
    company: "IMAGING BIOMETRICS, LL",
    panel_lead: "Radiology",
    primary_product_code: "LNW",
  },
  {
    id: "20",
    date_of_final_decision: "07/30/2011",
    submission_number: "K080896",
    device: "PATHWORK DIAGNOSTICS TISSUE OF ORIGIN TEST",
    company: "PATHWORK DIAGNOSTIC",
    panel_lead: "Clinical Toxicology",
    primary_product_code: "ORW",
  },
  {
    id: "21",
    date_of_final_decision: "07/30/2003",
    submission_number: "K083896",
    device: "PATHWORK DIAGNOSTICS TISSUE OF ORIGIN TEST",
    company: "PATHWORK DIAGNOSTIC",
    panel_lead: "Clinical Toxicology",
    primary_product_code: "OOW",
  },
];
